version: '3'
services:
 frontend:
    image: frontend:1.0
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000/api
    depends_on:
      - backend

 backend:
    image: backend:1.0
    ports:
      - "4000:4000"
    environment:
      - DB=mongodb://mongo:27017/mahekal
      - FRONTEND_URL="http://frontend:3000"
    depends_on:
      - mongo

 mongo:
    image: mongo:latest
    ports:
      - "27017:27017"