version: '3'
services:
  app:
    build: ./path/to/nodejs/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  client:
    build: ./path/to/react/app
    ports:
      - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
